package pharmacy2;


import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sunitha
 */
public class NewTransaction2 extends javax.swing.JFrame {
public static String date ="0/0/0";
    /**
     * Creates new form NewPurchase
     */
    public NewTransaction2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField6Code = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        codeButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        codeInput = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField6 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1440, 900));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel2.setText("Date:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1430, 10));

        jLabel6.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel6.setText("Total:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, -1, -1));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 248, -1));

        jLabel8.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel8.setText("Discount (if any):");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));

        jLabel7.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jLabel7.setText("Amount:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, -1));
        getContentPane().add(jTextField6Code, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 248, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 248, -1));

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Item Name", "Type", "Quantity(in strips)", "Price Per Unit", "Expiry Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 1210, 138));

        jLabel5.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel5.setText("Search:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jButton5.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jButton5.setText("Bill");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 530, 99, -1));

        codeButton.setFont(new java.awt.Font("Aharoni", 0, 36)); // NOI18N
        codeButton.setText("Enter");
        codeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(codeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

        jButton3.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jButton3.setText("Menu Page");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 290, -1, -1));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox1PropertyChange(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 119, -1));

        jButton4.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jButton4.setText("Undo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 370, -1, -1));

        jTextField4.setFocusable(false);
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 30, 37, -1));

        jLabel9.setText("/");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 30, 20, -1));

        codeInput.setFocusable(false);
        getContentPane().add(codeInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 180, -1));

        jTextField5.setFocusable(false);
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 30, 39, -1));

        jLabel10.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel10.setText("(Year/Month/Day)");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, -1, -1));

        jLabel11.setText("/");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 30, 20, -1));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jCheckBox1.setText("Special Customer");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 230, -1));

        jTextField6.setFocusable(false);
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 30, 40, -1));

        jButton6.setFont(new java.awt.Font("Aharoni", 0, 24)); // NOI18N
        jButton6.setText("Clear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        jLabel1.setText("To Other Enter 1 :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("BarCode :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
int id;
double amt=0.0,disc=0.0;
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
codeInput.setFocusable(true);
jComboBox1.removeAllItems();
jComboBox1.addItem("-Select Medicines-");
        try{
      Class.forName("java.sql.DriverManager" );
      Connection con=DriverManager.getConnection("jdbc:mysql://localhost/pharmacy2","root","");
      Statement stmt=con.createStatement();
      String query="select name from medicines;";
      ResultSet rs=stmt.executeQuery(query);
      while(rs.next()){
      jComboBox1.addItem(rs.getString(1));
      }
      
      String yearquery="select year(curdate()) as year;";
      ResultSet rs1=stmt.executeQuery(yearquery);
      if(rs1.next())
      jTextField6.setText(rs1.getString(1));
      String monthquery="select month(curdate()) as month;";
      ResultSet rs2=stmt.executeQuery(monthquery);
      if(rs2.next())
      jTextField4.setText(rs2.getString(1));
      String dayquery="select dayofmonth(curdate()) as day;";
      ResultSet rs3=stmt.executeQuery(dayquery);
      if(rs3.next())
      jTextField5.setText(rs3.getString(1));
      
      date=jTextField6.getText()+"/"+jTextField4.getText()+"/"+jTextField5.getText();
      
        }
       catch(Exception e){
     JOptionPane.showMessageDialog(null,e.getMessage());
     }        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
try{
      String meds=(String)jComboBox1.getSelectedItem();
      Class.forName("java.sql.DriverManager" );
      Connection con=DriverManager.getConnection("jdbc:mysql://localhost/pharmacy2","root","");
      Statement stmt=con.createStatement();
      String query="select * from medicines where name='"+meds+"';";
      ResultSet rs=stmt.executeQuery(query);
      int qnty=0;
      while(rs.next()){
      String med_code=rs.getString("barcode");
      int totqnty=rs.getInt("quantity");
      String man_name=rs.getString("type");
      double price=rs.getDouble("price");
      String date=rs.getString("expiration_date");
      String reply=JOptionPane.showInputDialog(null,"Total Quantity (in strips)is '"+totqnty+ "'","Enter Medicine Quantity",JOptionPane.PLAIN_MESSAGE);
      qnty=Integer.parseInt(reply);
      while(qnty>totqnty||qnty<0)
      {
          JOptionPane.showMessageDialog(null,"Enter valid Quantity ");
      String reply1=JOptionPane.showInputDialog(null,"Total Quantity (in strips)is '"+totqnty+ "'","Enter Medicine Quantity",JOptionPane.PLAIN_MESSAGE);
      qnty=Integer.parseInt(reply1);
      }
      model.addRow(new Object[] {med_code,meds,man_name,qnty,price,date});
      amt=amt+(price*qnty);
      }
      Statement stmt1=con.createStatement();
      String query2="update medicines set Quantity=Quantity-'"+qnty+"'";
      stmt1.executeUpdate(query2);}
     catch(Exception e){
     JOptionPane.showMessageDialog(null,e.getMessage());
     }
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void codeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeButtonActionPerformed
      DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try{
      String inputCode=codeInput.getText();
     // System.out.println("other "+inputCode);
      if("1".equals(inputCode)){//نثريات 
       //   System.out.println("other "+inputCode);
      //    Class.forName("java.sql.DriverManager" );
     // Connection con=DriverManager.getConnection("jdbc:mysql://localhost/pharmacy2","root","");
     // Statement stmt=con.createStatement();
//     JOptionPane.showMessageDialog(null,"Enter Price ");
      String reply1=JOptionPane.showInputDialog(null,"Enter Price","others",JOptionPane.PLAIN_MESSAGE);
       double priceInput=Double.parseDouble(reply1); 
    // Class.forName("java.sql.DriverManager" );
     // String query="select * from medicines where barcode='"+inputCode+"';";
     // ResultSet rs=stmt.executeQuery(query);
      //while(rs.next()){
     // String med_code=rs.getInt("barcode");
      String name="other";;
      int qnty=0;
      String man_name="other";
    //  double price=rs.getDouble("price");
      String date="other";
      model.addRow(new Object[] {inputCode,name,man_name,qnty,priceInput,date});
      amt=amt+(priceInput);
      //}
      //Statement stmt1=con.createStatement();
      //String query2="update medicines set price=price-'"+priceInput+"'";
      //stmt1.executeUpdate(query2);
      codeInput.setText("");
      }
      else{//barcode normal
      Class.forName("java.sql.DriverManager" );
      Connection con=DriverManager.getConnection("jdbc:mysql://localhost/pharmacy2","root","");
      Statement stmt=con.createStatement();
      String query="select * from medicines where barcode='"+inputCode+"';";
      ResultSet rs=stmt.executeQuery(query);
      int qnty=0;
      while(rs.next()){
     // String med_code=rs.getInt("barcode");
      String name=rs.getString("name");
      int totqnty=rs.getInt("quantity");
      String man_name=rs.getString("type");
      double price=rs.getDouble("price");
      String date=rs.getString("expiration_date");
      String reply=JOptionPane.showInputDialog(null,"Total Quantity is '"+totqnty+ "'","Enter Medicine Quantity",JOptionPane.PLAIN_MESSAGE);
      qnty=Integer.parseInt(reply);
      while(qnty>totqnty||qnty<0)
      {
          JOptionPane.showMessageDialog(null,"Enter valid Quantity ");
      String reply1=JOptionPane.showInputDialog(null,"Total Quantity is '"+totqnty+ "'","Enter Medicine Quantity",JOptionPane.PLAIN_MESSAGE);
      qnty=Integer.parseInt(reply1);
      }
      model.addRow(new Object[] {inputCode,name,man_name,qnty,price,date});
      amt=amt+(price*qnty);
      }
      Statement stmt1=con.createStatement();
      String query2="update medicines set quantity=quantity-'"+qnty+"'";
      stmt1.executeUpdate(query2);
      codeInput.setText("");
        }//end else
        }
     catch(Exception e){
     JOptionPane.showMessageDialog(null,e.getMessage());
     }
        
        //quantity -1 !!!
    }//GEN-LAST:event_codeButtonActionPerformed

    private void jComboBox1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1PropertyChange

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int rows = model.getRowCount();
        if(rows>0){
        String codeMed=String.valueOf(jTable1.getModel().getValueAt(rows-1,1));
        double price=Double.parseDouble(String.valueOf(jTable1.getModel().getValueAt(rows-1,4)));
        int qnty=Integer.parseInt(String.valueOf(jTable1.getModel().getValueAt(rows-1,3)));
        try{
            Class.forName("java.sql.DriverManager" );
      Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/pharmacy2","root","");
      Statement stmt=con.createStatement();
      String query="update medicines set quantity=quantity+'"+qnty+"' where barcode='"+codeMed+"'";
      stmt.executeUpdate(query);
      }
          catch(Exception e){
      JOptionPane.showMessageDialog(null, e.getMessage());
          }

        amt=amt-(price*qnty);
        model.removeRow(rows-1);
//        jButton1.doClick();
        }
        else
            JOptionPane.showMessageDialog(null,"No More Values To Undo");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
new menu_page2().setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 if(jCheckBox1.isSelected()==false){
      double total=amt-disc;
      jTextField6Code.setText(""+amt);
      jTextField7.setText(""+disc);
      jTextField8.setText(""+total);
}else{
 
      jTextField6Code.setText(""+amt);
     // jTextField7.setText(""+disc);//enter dis text!!!
      disc=Double.parseDouble(jTextField7.getText());
      if(jTextField7.getText()==""){
      disc=0.0;
      }
      double total=amt-disc;
      jTextField8.setText(""+total);
     }       
 DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
int rows = model.getRowCount();
Double subDay = 0.0;
 boolean flagNewDate=false;
 
if(jTextField6Code.getText().equals("")||jTextField7.getText().equals("")||jTextField8.getText().equals("")||rows==0)
       JOptionPane.showMessageDialog(null, "Enter All Details And Calculate Amount Before Proceeding.");
else{
try{
       date=jTextField6.getText()+"/"+jTextField4.getText()+"/"+jTextField5.getText();
      // BasicClass.date=date;
     Double TotlaDay=Double.parseDouble(jTextField8.getText());
      Class.forName("java.sql.DriverManager" );
      Connection con=DriverManager.getConnection("jdbc:mysql://localhost/pharmacy2","root","");
      Statement stmt=con.createStatement();
       //System.out.println("save0 .. ");
      String query="select * from totalbuy where day='"+date+"';";
      ResultSet rs=stmt.executeQuery(query);
      while(rs.next()){
//          System.out.println("save12 .. "+rs.getDouble("totalDay"));
      subDay=rs.getDouble("totalDay");
       flagNewDate=true;
  //     System.out.println("save22 .. "+rs.getDouble("totalDay"));
      }
      // System.out.println("save2 .. "+subDay);
       if(flagNewDate==true){
      subDay=subDay+TotlaDay;
    //  System.out.println("save3 .. "+subDay);
      String sqlquery3="update totalbuy set totalDay='"+subDay+"' where day='"+date+"'";
      stmt.executeUpdate(sqlquery3);
         JOptionPane.showMessageDialog(null,"update Bill Is okay."); 
       }
        // System.out.println("save4.. "+flagNewDate);
}
catch(Exception e){
   //  JOptionPane.showMessageDialog(null,e.getMessage());
     }
if(flagNewDate==false){
     try{
      String date=jTextField6.getText()+"/"+jTextField4.getText()+"/"+jTextField5.getText();
     Double TotlaDay=Double.parseDouble(jTextField8.getText());
     String monthInput=jTextField4.getText();
      Class.forName("java.sql.DriverManager" );
      Connection con=DriverManager.getConnection("jdbc:mysql://localhost/pharmacy2","root","");
      Statement stmt=con.createStatement();
      
       String sqlquery0="insert into totalbuy values('"+date+"','"+monthInput+"','"+TotlaDay+"')";
        System.out.println("flagNew==false "+flagNewDate);
      stmt.executeUpdate(sqlquery0);
     //  System.out.println("save1 .. "+sqlquery0);
         JOptionPane.showMessageDialog(null,"update Bill Is okay."); 
}
catch(Exception e){
     JOptionPane.showMessageDialog(null,e.getMessage());
     }
 }
}
//jTextField6Code.setText("");
//jTextField7.setText("");
//jTextField8.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
    if(jCheckBox1.isSelected()){
   // jTextField1.setFocusable(false);
    //jTextField2.setFocusable(false);
        jTextField7.setFocusable(true);
   // }
   // else{
  //  jTextField1.setFocusable(true);
   // jTextField2.setFocusable(true);
    }
        // TODO add your handling code here:
  //  jTextField6Code.setFocusable(true);
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int rows = model.getRowCount();
	if (rows > 0) {
            for (int i = 0; i <rows; i++) {
                model.removeRow(i);
            }
        }
        
        jTextField6Code.setText("");
         System.out.println("Hey .. ");
        jTextField7.setText("");
        jTextField8.setText("");
        amt=0;
        disc=0;
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewTransaction2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewTransaction2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewTransaction2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewTransaction2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewTransaction2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton codeButton;
    private javax.swing.JTextField codeInput;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField6Code;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
